version: '3.7'

services:
  protocolserver:
    build:
      context: ./
      dockerfile: docker/Dockerfile.server
    environment:
      - SERVER_HOST=0.0.0.0
    image: protocolserver
    container_name: protocolserver
    expose:
      - 8080
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: 'host'

  
  protocolclient:
    build:
      context: ./
      dockerfile: docker/Dockerfile.client
      args:
        SERVER_URL: "http://127.0.0.1:8080"
    image: protocolclient
    container_name: protocolclient
    depends_on:
      - protocolserver
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: 'host'
    restart: always

      





    
