FROM rust:1.74

WORKDIR  /zkp-protocol-app

COPY . .

USER root

EXPOSE 8080

RUN apt update
RUN apt install -y protobuf-compiler

RUN cargo install --bin server --path .
CMD RUST_LOG=info server

# $ rustup show
# RUN cargo intall --bin server --path .
# https://hub.docker.com/_/rust/

