FROM rust:1.74

WORKDIR /usr/src/zkp-protocol-app

COPY . .

RUN apt update
RUN apt install -y protobuf-compiler

RUN cargo build --release --bin client
CMD ["./target/release/client"]

# $ rustup show

