FROM rust:1.74

WORKDIR  /usr/src/zkp-protocol-app

COPY . .

USER root

RUN apt update
RUN apt install -y protobuf-compiler

RUN cargo build --release --bin server
CMD ["./target/release/server"]

# $ rustup show

