FROM rust:1.74

WORKDIR /zkp-protocol-app

COPY . .

RUN apt update
RUN apt install -y protobuf-compiler

RUN cargo install --bin client --path .
ENTRYPOINT [ "client", "--url",  "http://127.0.0.1:8080/" ]

# $ rustup show

